export const data = {
  pages: [
    {
      articles: [
        {
          _id: '1',
          headline: { main: 'Sample Headline 1' },
          source: 'Sample Source 1',
          byline: { original: 'by Author 1' },
          pub_date: '2023-10-13T17:25:43+0000',
          web_url: 'http://sample.url/1',
        },
        {
          _id: '2',
          headline: { main: 'Sample Headline 2' },
          source: 'Sample Source 2',
          byline: { original: 'by Author 2' },
          pub_date: '2023-10-13T17:25:44+0000',
          web_url: 'http://sample.url/2',
        },
        {
          _id: '3',
          headline: { main: 'Sample Headline 3' },
          source: 'Sample Source 3',
          byline: { original: 'by Author 3' },
          pub_date: '2023-10-13T17:25:44+0000',
          web_url: 'http://sample.url/3',
        },
        {
          _id: '4',
          headline: { main: 'Sample Headline 4' },
          source: 'Sample Source 4',
          byline: { original: 'by Author 4' },
          pub_date: '2023-10-13T17:25:44+0000',
          web_url: 'http://sample.url/4',
        },
        {
          _id: '5',
          headline: { main: 'Sample Headline 5' },
          source: 'Sample Source 5',
          byline: { original: 'by Author 5' },
          pub_date: '2023-10-13T17:25:44+0000',
          web_url: 'http://sample.url/5',
        },
        {
          _id: '6',
          headline: { main: 'Sample Headline 6' },
          source: 'Sample Source 6',
          byline: { original: 'by Author 6' },
          pub_date: '2023-10-13T17:25:44+0000',
          web_url: 'http://sample.url/6',
        },
        {
          _id: '7',
          headline: { main: 'Sample Headline 7' },
          source: 'Sample Source 7',
          byline: { original: 'by Author 7' },
          pub_date: '2023-10-13T17:25:44+0000',
          web_url: 'http://sample.url/7',
        },
        {
          _id: '8',
          headline: { main: 'Sample Headline 8' },
          source: 'Sample Source 8',
          byline: { original: 'by Author 8' },
          pub_date: '2023-10-13T17:25:44+0000',
          web_url: 'http://sample.url/2',
        },
        {
          _id: '9',
          headline: { main: 'Sample Headline 8' },
          source: 'Sample Source 8',
          byline: { original: 'by Author 8' },
          pub_date: '2023-10-13T17:25:44+0000',
          web_url: 'http://sample.url/8',
        },

        {
          _id: '10',
          headline: { main: 'Sample Headline 9' },
          source: 'Sample Source 9',
          byline: { original: 'by Author 9' },
          pub_date: '2023-10-13T17:25:51+0000',
          web_url: 'http://sample.url/9',
        },
        {
          _id: '11',
          headline: { main: 'Sample Headline 10' },
          source: 'Sample Source 10',
          byline: { original: 'by Author 10' },
          pub_date: '2023-10-13T17:25:52+0000',
          web_url: 'http://sample.url/10',
        },
      ],
    },
  ],
};
