import dynamic from 'next/dynamic';
import Head from 'next/head';

const Layout = dynamic(() => import('@/components/layout/Layout'), {
  ssr: false,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>신하영 FE과제</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout />
    </>
  );
}
